################ English language ##################
[en]
label = "En"
locale = "en-us"
contentDir = "content/english"
weight = 2

################ French language ##################
[fr]
label = "Fr"
locale = "fr-fr"
contentDir = "content/french"
weight = 1

